FPS = 60

MAX_PLAYERS = 4

SCREEN_WIDTH = 765
SCREEN_HEIGHT = 675

ARENA_WIDTH = 17
ARENA_HEIGHT = 15

BOMB_TIMER = 100
EXPLOSION_DURATION = 30

# -----------------internal defines-----------------
TILE_SIZE = 45

LEFT_BORDER_X = 22
RIGHT_BORDER_X = 652

UP_BORDER_Y = 0
DOWN_BORDER_Y = 540

CELL_WIDTH = 90

PLAYER_FRAME_DURATION = 0.2
PLAYER_DIE_FRAME_DURATION = 0.15

BOMB_FRAME_DURATION = 0.25
EXPLOSION_FRAME_DURATION = 0.1
