class Event:
	SERVER_FULL = "full"
	EXIT = "exit"
	MOVE_UP = "up"
	MOVE_DOWN = "down"
	MOVE_LEFT = "left"
	MOVE_RIGHT = "right"
	PLACE_BOMB = "bomb"
	DIE = "die"
	START = "start"
	OTHER_PLAYER_JOINED = "joined"